name: Findi CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Deps
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Build
        run: cargo build --verbose --release --all-features
      - name: Run tests
        run: cargo test --verbose
